################################################################################
# Makefile for building and running docker containers

production_build:
	docker build --no-cache -t mazamascience/productionutils:0.0.0.9000 .

